name = "MarketStore"
uuid = "97b6ba83-397a-4ae4-b067-49e1ee77ae56"
authors = ["D3MZ <arrrwalktheplank@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
